# Generated by Django 6.0.2 on 2026-02-26 11:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('salary', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('applied', '📨 Applied'), ('interview', '📞 Interview Scheduled'), ('offer', '🎉 Offer Received'), ('rejected', '❌ Rejected'), ('withdrawn', '🔙 Withdrawn')], default='applied', max_length=20)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('job_url', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_date'],
            },
        ),
    ]
