name: SmartHire CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./SmartHire/SmartHire

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: pip install -r ../../requirements.txt

    - name: Run Django Check
      run: python manage.py check

    - name: Success Message
      run: echo "SmartHire Pipeline Successful!"